name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Login to NPM
        run: |
          echo '' >> ~/.npmrc
          echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}' >> ~/.npmrc
          cat ~/.npmrc

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm -v
          npm install
        env:
          CI: true

      - name: Build
        run: |
          ./node_modules/.bin/node-ts-scripts bundle src/index.ts --outputDir=build --dts
        env:
          CI: true

      - name: Create Changelogs
        if: |
          github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: changelog
        uses: heineiuo/create-changelogs@master

      - name: Publish to NPM
        if: |
          github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          npm publish --access=public

      - name: Create Release
        if: |
          github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelogs }}
          draft: false
          prerelease:
            ${{ steps.changelog.outputs.release_type == 'prerelease' }}

